# Generated by Django 6.1 on 2026-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
