# Generated by Django 6.1 on 2026-09-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariopersonalizado_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='rol',
        ),
    ]
