[project]
name = "tp-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tomas", email = "t.alonsoarias@itecriocuarto.org.ar" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
    "djangorestframework==3.18.0",
    "djangorestframework-simplejwt==5.5.1",
]

[project.scripts]
tp-1 = "tp_1:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
