# Generated by Django 6.1 on 2026-09-09 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='usuario_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutina', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutinapersonalizada',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutinapersonalizada',
            name='usuario_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutina_usuario_activo', to=settings.AUTH_USER_MODEL),
        ),
    ]
